# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.10
_src_path: ../../ModernAppTemplate/frontend
author_email: pvginkel@gmail.com
author_name: Pieter van Ginkel
backend_port: 3001
frontend_port: 3000
image_name: registry:5000/electronics-inventory-ui
project_description: Electronics Inventory
project_name: electronics-inventory
project_title: Electronics
repo_url: https://github.com/pvginkel/ElectronicsInventoryUI.git
sse_gateway_port: 3002
use_app_shell: true
use_oidc: true
use_sse: true
